baseURL = "https://whoisjustinngo.github.io/"
title = "Musings"
theme = "salinger"

[params]

author = "Justin Ngo"
#googleAnalytics = ""
twemoji = true
text404 = "It looks like the page you're looking for doesn't exist. Go <a href=\"/\">home</a>."

DateFormat = "Jan 2006"

#mainMenuSvg = '''
#<svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ece9e9}</style><path d="M464 256A208 208 0 1 0 48 256a208 208 0 1 0 416 0zM0 256a256 256 0 1 1 512 0A256 256 0 1 1 0 256zm306.7 69.1L162.4 380.6c-19.4 7.5-38.5-11.6-31-31l55.5-144.3c3.3-8.5 9.9-15.1 18.4-18.4l144.3-55.5c19.4-7.5 38.5 11.6 31 31L325.1 306.7c-3.2 8.5-9.9 15.1-18.4 18.4zM288 256a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/></svg>
#'''




mainMenuShowThemes = false
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true
showOnlyFeaturedPost = false

filterCoverImages = true

[params.meta]
title = "Salinger Theme for Hugo built with TailwindCSS and DaisyUI"
description = "Salinger is a clean, minimalistic, mobile-first, blazing-fast, fancy and lightweight theme for the Hugo framework built with TailwindCSS and DaisyUI"
keywords = ["simple", "minimal", "clean", "fast", "blog", "portfolio", "responsive", "twemoji", "recursion", "section", "tailwind", "daisyui"]

[params.footer]
copy = 'Justin Ngo. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" class="link">Some rights reserved.</a>'

[[params.social]]

name = "LinkedIn"
url = "https://www.linkedin.com/in/justin-ngo-359397202/"
icon = "fa-brands fa-linkedin"
featured = true # true to be displayed in the home hero.

[Menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "About me"
url = "/posts/Hello_world"
weight = 2

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy"
weight= 1 

[taxonomies]
tags = "tags"


# the following code is mandatory for the theme to work properly.

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'